name: run unit tests of feature branches

on:
  push:
    branches:
      'feature/*'
      
jobs:
  run-unit-test: #job ID
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        
      - name: run unit test
        run: mvn test
